// Fork as a verb: a copy that moves no bytes, remembers where it came from, and belongs to
// whoever made it.
//
// `F-fork-verb`. Forking existed here twice already and neither one was a verb — conflict
// RESOLUTION (`C-fork-on-conflict`) and "an agent copies a folder and republishes it", which
// needs a repo, a checkout, and an upload of every byte for content the store already holds.
//
// THE THREE CLAUSES THIS FILE HAS TO PROVE, and each is measured rather than asserted:
//
//   1. A HUNDRED-FILE FORK TRANSFERS ZERO BLOB BYTES, and the fork serves immediately. The
//      store below COUNTS every touch of a `blobs/` key — put, get and head — so "no bytes
//      moved" is a number this file reads back, not a property inferred from the code. The
//      serving half is the real `assetFetch` answering the forked URL with the source's
//      bytes, plus the gate agreeing the new prefix is public.
//   2. THE MANIFEST CARRIES `forkedFrom {path, version}` AND NAMES NOBODY BY ADDRESS. The
//      owner is a `personId`, the same one-way hash a message carries — the deviation
//      `C-manifest-provenance` recorded, for the same reason: a manifest is read by more
//      things than a comment thread is. `publishedBy` is the one field that has always held
//      an address and has its own erasure path; the test pins it as the ONLY one, so a
//      later field that smuggles a second address in fails here.
//   3. A PRE-EXISTING MANIFEST WITH NO LINEAGE RENDERS EXACTLY AS TODAY. That one is
//      `test/manifest-lineage-compat.test.mjs`, against a baseline generated by the code
//      that predates the fields.
//
// And the trap that is not in any clause: LINEAGE HAS TO SURVIVE THE NEXT ORDINARY PUBLISH.
// A publisher's manifest is built from their own tree, which has never heard of a fork
// somebody else made — so a commit taking `routing` verbatim would keep the fork's files
// serving while dropping its parentage and its owner. The last group here is that.
import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { __testables as W } from "../src/_worker.js";

const sha = (s) => createHash("sha256").update(s).digest("hex");
const file = (body, ct = "text/html; charset=utf-8") => ({ h: sha(body), ct, s: body.length });

// A workspace id of its own per test, because the manifest cache is keyed on it and a
// neighbour's view would make a "serves immediately" assertion vacuous.
let n = 0;
const tenant = () => `fork-verb-${++n}`;

const ADA = { email: "ada@example.test", name: "Ada", initials: "AD", role: "editor" };
const ctxFor = (tenantId) => ({ ...W.applyInstance({ users: [ADA] }), tenantId });

/**
 * The store, with a turnstile on the blob pool.
 *
 * Every read, write and existence check of a `blobs/` key is counted separately from the
 * manifest traffic, so clause 1 is a measurement: `blobs` must still read {0,0,0} after a
 * hundred-file fork, and `bytes` must still be 0.
 */
function countingR2(initial = {}) {
  const store = new Map(Object.entries(initial));
  const etags = new Map([...store.keys()].map((k) => [k, "e0"]));
  let seq = 0;
  const blobs = { puts: 0, gets: 0, heads: 0, bytes: 0 };
  const isBlob = (k) => String(k).startsWith("blobs/");
  return {
    store, blobs,
    reset() { blobs.puts = blobs.gets = blobs.heads = blobs.bytes = 0; },
    async get(k) {
      if (isBlob(k)) blobs.gets++;
      if (!store.has(k)) return null;
      const v = store.get(k);
      return { text: async () => v, body: v, etag: etags.get(k) };
    },
    async put(k, v) {
      const text = typeof v === "string" ? v
        : (v && v.byteLength !== undefined ? new TextDecoder().decode(v) : JSON.stringify(v));
      if (isBlob(k)) { blobs.puts++; blobs.bytes += text.length; }
      store.set(k, text);
      etags.set(k, `e${++seq}`);
    },
    async head(k) {
      if (isBlob(k)) blobs.heads++;
      return store.has(k) ? { etag: etags.get(k) } : null;
    },
    async list({ prefix = "", delimiter } = {}) {
      const keys = [...store.keys()].filter((k) => k.startsWith(prefix));
      if (delimiter) {
        const set = new Set();
        for (const k of keys) {
          const i = k.indexOf(delimiter, prefix.length);
          if (i >= 0) set.add(k.slice(0, i + 1));
        }
        return { delimitedPrefixes: [...set], objects: [], truncated: false };
      }
      return { objects: keys.map((k) => ({ key: k })), truncated: false };
    },
  };
}

/** One unit of `count` files, whose bytes name the unit and the index. */
function unitFiles(unit, count) {
  const files = { [`${unit}index.html`]: file(`<h1>${unit}</h1>`) };
  for (let i = 1; i < count; i++) {
    files[`${unit}asset-${i}.js`] = file(`// ${unit} file ${i}`, "application/javascript; charset=utf-8");
  }
  return files;
}

function manifestOf(version, units, extra = {}) {
  const files = {};
  for (const [u, count] of Object.entries(units)) Object.assign(files, unitFiles(u, count));
  return {
    id: "alpha", version, format: 1,
    space: { id: "alpha", default: true, adminOnly: false, name: "Alpha" },
    source: { sha: "a".repeat(40), dirty: false },
    builtWith: { engine: "e".repeat(40), version: "0.15.0" },
    publishedAt: "2026-08-20T09:14:02.000Z",
    publishedBy: ADA.email,
    files,
    routing: { publicPrefixes: Object.keys(units), versionMap: {}, unitSources: {}, ...(extra.routing || {}) },
    ...extra.top,
  };
}

/** A store holding one live manifest and a blob behind every hash it names. */
function fleet(live) {
  const objects = { "spaces/alpha/manifest.json": JSON.stringify(live) };
  for (const [p, f] of Object.entries(live.files)) objects[`blobs/${f.h}`] = `bytes of ${p}`;
  return { GV_ASSET_SOURCE: "r2", BUNDLES: countingR2(objects) };
}

const call = (ctx, env, op, body, token = "tok") => W.publishApi(
  ctx,
  new Request(`https://x.test/__publish/alpha/${op}`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "content-type": "application/json" },
    body: JSON.stringify(body),
  }),
  new URL(`https://x.test/__publish/alpha/${op}`),
  env);

const liveNow = (env) => JSON.parse(env.BUNDLES.store.get("spaces/alpha/manifest.json"));

/**
 * A real publish token, in KV, labelled with a real address — because the point of clause 2
 * is that the address the CREDENTIAL carries never reaches the manifest. A bootstrap token
 * is labelled "bootstrap" and would make that impossible to see.
 */
async function withToken(env, label = ADA.email, space = "alpha") {
  const map = new Map();
  env.COMMENTS = {
    async get(k) { return map.has(k) ? map.get(k) : null; },
    async getWithMetadata(k) { return { value: map.get(k) ?? null, metadata: null }; },
    async put(k, v) { map.set(k, typeof v === "string" ? v : JSON.stringify(v)); },
    async delete(k) { map.delete(k); },
    async list({ prefix = "" } = {}) {
      return { keys: [...map.keys()].filter((k) => k.startsWith(prefix)).map((name) => ({ name })), list_complete: true };
    },
  };
  map.set("publish:tokens", JSON.stringify({ [await W.tokenFor("pub:tok")]: { space, label } }));
  return env;
}

// ── clause 1: a hundred files, zero bytes, serving immediately ──────────────────────────

test("A 100-FILE PROTOTYPE FORKS WITHOUT MOVING ONE BLOB BYTE", async () => {
  const t = tenant(), ctx = ctxFor(t);
  const live = manifestOf(41, { "/toolkit/map/": 100, "/playground/sketch/": 3 });
  const env = await withToken(fleet(live));
  assert.equal(Object.keys(unitFiles("/toolkit/map/", 100)).length, 100, "the fixture is not 100 files");

  const before = liveNow(env);
  env.BUNDLES.reset();
  const res = await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" });
  const body = await res.json();
  assert.equal(res.status, 200, JSON.stringify(body));

  // THE MEASUREMENT. Not "no upload endpoint was called" — no key under blobs/ was touched
  // at all, in any direction, so there was nothing to transfer.
  assert.deepEqual(
    { puts: env.BUNDLES.blobs.puts, gets: env.BUNDLES.blobs.gets, heads: env.BUNDLES.blobs.heads, bytes: env.BUNDLES.blobs.bytes },
    { puts: 0, gets: 0, heads: 0, bytes: 0 },
    "a fork touched the blob pool");
  assert.equal(body.blobsUploaded, 0);
  assert.equal(body.files, 100, "the fork did not alias every file of the unit");

  // The second, independent measurement: bytesReferenced deduplicates by hash, so a fork
  // that had really copied content would move it.
  const after = liveNow(env);
  assert.ok(W.bytesReferencedOf(before) > 0, "the fixture references no bytes, so the next line proves nothing");
  assert.equal(after.bytesReferenced, W.bytesReferencedOf(before),
    "the fork changed what the space references");
  assert.equal(
    new Set(Object.values(after.files).map((f) => f.h)).size,
    new Set(Object.values(before.files).map((f) => f.h)).size,
    "the fork introduced a hash the store did not already have");
  assert.equal(Object.keys(after.files).length, Object.keys(before.files).length + 100);
});

test("and it serves at its new URL immediately, with the source's own bytes", async () => {
  const t = tenant(), ctx = ctxFor(t);
  const live = manifestOf(41, { "/toolkit/map/": 100 });
  const env = await withToken(fleet(live));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);

  // No cache warm-up, no second publish: the commit path busts this workspace's manifest
  // view, so the very next request answers from the new manifest.
  const page = await W.assetFetch(t, env, new Request("https://x.test/toolkit/map-mine/index.html"));
  assert.equal(page.status, 200);
  assert.equal(await page.text(), "bytes of /toolkit/map/index.html",
    "the fork served something other than the blob the source points at");
  const asset = await W.assetFetch(t, env, new Request("https://x.test/toolkit/map-mine/asset-7.js"));
  assert.equal(asset.status, 200);
  assert.equal(asset.headers.get("Content-Type"), "application/javascript; charset=utf-8");
  const dir = await W.assetFetch(t, env, new Request("https://x.test/toolkit/map-mine/"));
  assert.equal(dir.status, 200, "the fork's folder URL does not resolve to its index");

  // And the gate opens it to anonymous visitors, which is what "serves" means for a link
  // somebody pastes somewhere.
  const gate = W.applyDerivedRouting(await W.loadManifests(t, env, true));
  assert.equal(W.isPublicPath(gate, "/toolkit/map-mine/index.html"), true);
  assert.equal(W.isPublicPath(gate, "/toolkit/map/index.html"), true, "the source stopped being public");
});

// ── clause 2: lineage, ownership, and no address anywhere it is written ─────────────────

test("THE FORK'S MANIFEST NAMES ITS PARENT BY PATH AND VERSION", async () => {
  const ctx = ctxFor(tenant());
  const live = manifestOf(41, { "/toolkit/map/": 4 });
  const env = await withToken(fleet(live));
  const body = await (await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).json();

  const m = liveNow(env);
  assert.deepEqual(m.routing.forkedFrom["/toolkit/map-mine/"], { path: "/toolkit/map/", version: 41 });
  assert.deepEqual(body.forkedFrom, { path: "/toolkit/map/", version: 41 });
  // v41 is a manifest the store still holds — versions are never pruned — so the parent
  // stays recoverable even after the source moves on.
  assert.equal(m.version, 42, "a fork is a publish and gets the next version");
  assert.equal(m.routing.publicPrefixes.includes("/toolkit/map-mine/"), true);
  assert.equal(JSON.parse(env.BUNDLES.store.get("spaces/alpha/versions/42.json")).version, 42);
});

test("the forker is stamped as the new unit's OWNER — a copy escapes the original's acl", async () => {
  const ctx = ctxFor(tenant());
  const live = manifestOf(41, { "/toolkit/map/": 4 }, { routing: { unitOwners: { "/toolkit/map/": "0000" } } });
  const env = await withToken(fleet(live));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);

  const owners = liveNow(env).routing.unitOwners;
  assert.equal(owners["/toolkit/map-mine/"], W.personId(ADA.email));
  assert.notEqual(owners["/toolkit/map-mine/"], owners["/toolkit/map/"],
    "the fork inherited the acl it was forked to escape");
  assert.equal(owners["/toolkit/map/"], "0000", "the source's owner moved");
});

test("A PERSON IS A personId AND NEVER AN ADDRESS — everywhere this item writes one", async () => {
  const ctx = ctxFor(tenant());
  const live = manifestOf(41, { "/toolkit/map/": 4 });
  const env = await withToken(fleet(live));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);
  const m = liveNow(env);

  // The fields this item adds: no address, at all.
  const added = JSON.stringify({ forkedFrom: m.routing.forkedFrom, unitOwners: m.routing.unitOwners });
  assert.doesNotMatch(added, /@/, "an address reached the lineage or the ownership record");
  assert.match(m.routing.unitOwners["/toolkit/map-mine/"], /^[0-9a-z]+$/);

  // And the whole manifest carries exactly ONE address-bearing field: `publishedBy`, which
  // predates all of this and is what `redactProvenance` erases on request. Pinning it as the
  // only one is what makes a future field that smuggles a second address in fail here.
  const withAddress = Object.entries(m).filter(([, v]) => JSON.stringify(v ?? null).includes("@")).map(([k]) => k);
  assert.deepEqual(withAddress, ["publishedBy"], "a manifest field other than publishedBy holds an address");
  assert.doesNotMatch(JSON.stringify(m.files), /@/, "a per-file stamp holds an address");
});

test("the aliased files keep the SOURCE's provenance stamp — copying is not editing", async () => {
  const ctx = ctxFor(tenant());
  const live = manifestOf(41, { "/toolkit/map/": 3 });
  live.files["/toolkit/map/index.html"].by = "9z8y7x";
  live.files["/toolkit/map/index.html"].editedAt = "2026-08-11T17:02:44.000Z";
  const env = await withToken(fleet(live));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);

  const f = liveNow(env).files["/toolkit/map-mine/index.html"];
  // Restamping a hundred unchanged files with the forker is exactly the "a mass commit reset
  // every card to edited-now" failure C-manifest-provenance exists to retire. WHO MADE THE
  // COPY is `unitOwners`, and it is a different fact.
  assert.equal(f.by, "9z8y7x");
  assert.equal(f.editedAt, "2026-08-11T17:02:44.000Z");
  // A file that predates the field stays unstamped rather than acquiring an invented one.
  assert.equal("by" in liveNow(env).files["/toolkit/map-mine/asset-1.js"], false);
});

// ── what a fork refuses ────────────────────────────────────────────────────────────────

const refusal = async (body, status, error) => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3, "/toolkit/chart/": 2 })));
  const res = await call(ctx, env, "fork", body);
  const got = await res.json();
  assert.equal(res.status, status, JSON.stringify(got));
  assert.equal(got.error, error);
  assert.equal(liveNow(env).version, 41, "a refused fork still published something");
};

test("a source that is not a live unit is a 404, not an empty copy", () =>
  refusal({ from: "/toolkit/nope/", to: "/toolkit/mine/" }, 404, "unknown-unit"));
test("a target that already exists is a 409 — a fork never overwrites", () =>
  refusal({ from: "/toolkit/map/", to: "/toolkit/chart/" }, 409, "fork-target-exists"));
test("a fork may not nest inside its source, or contain it", () =>
  refusal({ from: "/toolkit/map/", to: "/toolkit/map/inner/" }, 400, "bad-fork-path"));
test("the site root is not an artifact", () =>
  refusal({ from: "/toolkit/map/", to: "/" }, 400, "bad-routing-prefix"));
test("engine chrome is not a fork target, star scope or not", () =>
  refusal({ from: "/toolkit/map/", to: "/admin/" }, 400, "bad-routing-prefix"));
test("`-conflict-` names belong to conflict forks and cannot be claimed by hand", () =>
  refusal({ from: "/toolkit/map/", to: "/toolkit/map-conflict-ada/" }, 400, "bad-fork-path"));
test("a fork target needing an escape is refused rather than guessed at", () =>
  refusal({ from: "/toolkit/map/", to: "/toolkit/a b/" }, 400, "bad-fork-path"));
test("a body with no paths in it is a 400", () =>
  refusal({ from: "/toolkit/map/" }, 400, "bad-fork-body"));

test("a token scoped to another space cannot fork in this one", async () => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3 })), ADA.email, "beta");
  const res = await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/mine/" });
  assert.equal(res.status, 403);
});

test("a capability-restricted credential cannot fork — a new verb starts closed", async () => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3 })), "purge-job", "*");
  const map = JSON.parse(await env.COMMENTS.get("publish:tokens"));
  for (const k of Object.keys(map)) map[k].caps = ["purge"];
  await env.COMMENTS.put("publish:tokens", JSON.stringify(map));
  const res = await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/mine/" });
  assert.equal(res.status, 403);
  assert.equal((await res.json()).reason, "capability-not-granted");
});

// ── the trap: lineage has to survive every later publish ───────────────────────────────

test("AN ORDINARY PUBLISH AFTERWARDS DOES NOT ERASE THE FORK'S PARENTAGE", async () => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3 })));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);

  // What a publisher's own build produces: every live unit including the fork (protocol 5
  // composes on top of live), and no lineage — their tree has never heard of it.
  const next = liveNow(env);
  delete next.routing.forkedFrom;
  delete next.routing.unitOwners;
  delete next.version;
  next.files["/toolkit/map/index.html"] = file("<h1>edited</h1>");
  for (const f of Object.values(next.files)) env.BUNDLES.store.set(`blobs/${f.h}`, "x");
  const res = await call(ctx, env, "commit", next);
  assert.equal(res.status, 200, await res.text());

  const after = liveNow(env);
  assert.deepEqual(after.routing.forkedFrom["/toolkit/map-mine/"], { path: "/toolkit/map/", version: 41 });
  assert.equal(after.routing.unitOwners["/toolkit/map-mine/"], W.personId(ADA.email));
});

test("and a manifest that CLAIMS an owner has the claim discarded — an acl is not typeable", async () => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3 })));
  const next = liveNow(env);
  delete next.version;
  next.routing.unitOwners = { "/toolkit/map/": "attacker" };
  next.routing.forkedFrom = { "/toolkit/map/": { path: "/elsewhere/", version: 9 } };
  for (const f of Object.values(next.files)) env.BUNDLES.store.set(`blobs/${f.h}`, "x");
  assert.equal((await call(ctx, env, "commit", next)).status, 200);

  const after = liveNow(env);
  assert.equal(after.routing.unitOwners, undefined, "a request wrote an owner");
  assert.equal(after.routing.forkedFrom, undefined, "a request wrote a lineage record");
});

test("A RESTORE INTO AN EMPTY STORE KEEPS THE FORKS IT IS RESTORING", async () => {
  // `augur restore` — and the migration built on it — replays an exported manifest as an
  // ordinary publish. Without trust-on-first-publish a moved workspace would arrive with its
  // forks still serving and their parentage and owners silently gone.
  const ctx = ctxFor(tenant());
  const exported = manifestOf(9, { "/toolkit/map/": 2, "/toolkit/map-mine/": 2 }, {
    routing: {
      forkedFrom: { "/toolkit/map-mine/": { path: "/toolkit/map/", version: 4 } },
      unitOwners: { "/toolkit/map-mine/": "bw5x51" },
    },
  });
  const env = await withToken({ GV_ASSET_SOURCE: "r2", BUNDLES: countingR2({}) });
  for (const f of Object.values(exported.files)) env.BUNDLES.store.set(`blobs/${f.h}`, "x");
  const { version, publishedAt, publishedBy, ...body } = exported;
  assert.equal((await call(ctx, env, "commit", body)).status, 200);

  const after = liveNow(env);
  assert.deepEqual(after.routing.forkedFrom, { "/toolkit/map-mine/": { path: "/toolkit/map/", version: 4 } });
  assert.deepEqual(after.routing.unitOwners, { "/toolkit/map-mine/": "bw5x51" });
});

test("but even a first publish cannot assert an address, a stranger unit, or a nonsense row", async () => {
  const ctx = ctxFor(tenant());
  const first = manifestOf(1, { "/toolkit/map/": 2 }, {
    routing: {
      forkedFrom: { "/toolkit/map/": { path: "/x/", version: "nine" }, "/never/": { path: "/x/", version: 1 } },
      unitOwners: { "/toolkit/map/": "someone@example.test", "/never/": "aaa" },
    },
  });
  const env = await withToken({ GV_ASSET_SOURCE: "r2", BUNDLES: countingR2({}) });
  for (const f of Object.values(first.files)) env.BUNDLES.store.set(`blobs/${f.h}`, "x");
  delete first.version;
  assert.equal((await call(ctx, env, "commit", first)).status, 200);

  const after = liveNow(env);
  assert.equal(after.routing.forkedFrom, undefined, "a malformed version or an undeclared unit was accepted");
  assert.equal(after.routing.unitOwners, undefined, "an address was accepted as an owner");
  assert.doesNotMatch(JSON.stringify(after.routing), /@/);
});

test("and a SECOND publish can no longer assert anything — the store decides from here", async () => {
  const ctx = ctxFor(tenant());
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 2 })));
  const next = liveNow(env);
  delete next.version;
  next.routing.unitOwners = { "/toolkit/map/": "attacker" };
  for (const f of Object.values(next.files)) env.BUNDLES.store.set(`blobs/${f.h}`, "x");
  assert.equal((await call(ctx, env, "commit", next)).status, 200);
  assert.equal(liveNow(env).routing.unitOwners, undefined);
});

test("deleting a forked unit takes its lineage and its owner with it", async () => {
  const t = tenant(), ctx = ctxFor(t);
  const env = await withToken(fleet(manifestOf(41, { "/toolkit/map/": 3 })));
  assert.equal((await call(ctx, env, "fork", { from: "/toolkit/map/", to: "/toolkit/map-mine/" })).status, 200);
  const removed = await W.removeFromStore({ ...ctx, INSTANCE_SENTINELS: [] }, env, "alpha", "/toolkit/map-mine/", "ada");
  assert.equal(removed.removed, 3);
  const after = liveNow(env);
  // An owner left behind for a resource that no longer exists would be inherited by whatever
  // is published at that path next.
  assert.deepEqual(after.routing.unitOwners, {});
  assert.deepEqual(after.routing.forkedFrom, {});
});

// ── the pure composer, on the cases a route cannot reach ───────────────────────────────

test("composeFork copies the source's versionMap and unit source, and nothing else's", () => {
  const live = manifestOf(7, { "/toolkit/map/": 2, "/toolkit/chart/": 2 }, {
    routing: {
      versionMap: { "/toolkit/map/": "v3", "/toolkit/chart/": "v9" },
      unitSources: { "/toolkit/map/": { sha: "b".repeat(40), dirty: true } },
    },
  });
  const { manifest } = W.composeFork({ live, from: "/toolkit/map/", to: "/toolkit/mine/", by: "abc" });
  assert.equal(manifest.routing.versionMap["/toolkit/mine/"], "v3");
  assert.deepEqual(manifest.routing.unitSources["/toolkit/mine/"], { sha: "b".repeat(40), dirty: true });
  assert.equal(manifest.routing.publicPrefixes.includes("/toolkit/chart/"), true);
  assert.equal(manifest.routing.forkedFrom["/toolkit/chart/"], undefined);
  // The live manifest handed in is never mutated — a composer that edited its input would
  // corrupt the very manifest a refusal has to leave untouched.
  assert.equal(live.routing.forkedFrom, undefined);
  assert.equal(Object.keys(live.files).length, 4);
});

test("a unit whose prefix has no files behind it is not forkable", () => {
  const live = manifestOf(7, { "/toolkit/map/": 2 });
  live.routing.publicPrefixes.push("/toolkit/ghost/");
  assert.equal(W.composeFork({ live, from: "/toolkit/ghost/", to: "/toolkit/mine/" }).error, "unknown-unit");
});

test("a source named without its trailing slash, or percent-encoded, still resolves", () => {
  const live = manifestOf(7, { "/toolkit/map/": 2 });
  assert.equal(W.composeFork({ live, from: "/toolkit/map", to: "/toolkit/mine/" }).error, undefined);
  const enc = manifestOf(7, { "/toolkit/ma%20p/": 2 });
  const got = W.composeFork({ live: enc, from: "/toolkit/ma p/", to: "/toolkit/mine/" });
  assert.equal(got.error, undefined);
  assert.equal(got.from, "/toolkit/ma%20p/", "the manifest's own spelling of the unit was not used");
});

test("carriedLineage keeps only what the next manifest still serves", () => {
  const cur = { routing: { forkedFrom: { "/a/": { path: "/x/", version: 1 }, "/b/": { path: "/y/", version: 2 } },
    unitOwners: { "/a/": "aa", "/b/": "bb" } } };
  const kept = W.carriedLineage(cur, { publicPrefixes: ["/a/"] });
  assert.deepEqual(kept, { forkedFrom: { "/a/": { path: "/x/", version: 1 } }, unitOwners: { "/a/": "aa" } });
  assert.deepEqual(W.carriedLineage({}, { publicPrefixes: ["/a/"] }), {});
});
