// A manifest that carries no lineage renders exactly as it did before lineage existed.
//
// `F-fork-verb` adds two OPTIONAL unit-level routing maps — `forkedFrom` (where a unit was
// copied from) and `unitOwners` (who owns it). Additive and optional is a claim, not a
// property: the whole point is that there is no flag day, and the only way to know a
// vintage manifest still means what it meant is to render one and compare.
//
// THE BASELINE IN `test/fixtures/pre-fork-render.baseline.json` WAS GENERATED BY THE CODE
// THAT PREDATES THE FIELDS, and it records the sha it was generated at. So this is a real
// before/after rather than a snapshot of the new behaviour asserting it is the old one.
// The fixture beside it is a manifest in the shape a live instance holds today: two units,
// a file that predates per-file provenance and therefore carries no stamp at all, an
// address in `publishedBy`, and an `_engine` fragment.
//
// WHAT IT COMPARES is the four things a manifest is read by: the routing derivation, the
// public `/_build.json` stamp, the gate's own verdicts, and the bytes and headers the
// store actually serves.
//
// TO REGENERATE (only ever with a reason, and never in the same commit as a behaviour
// change): `node test/manifest-lineage-compat.test.mjs --write`.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { __testables as W } from "../src/_worker.js";

const FIXTURE = fileURLToPath(new URL("./fixtures/manifest-pre-fork.json", import.meta.url));
const BASELINE = fileURLToPath(new URL("./fixtures/pre-fork-render.baseline.json", import.meta.url));

const manifests = () => JSON.parse(fs.readFileSync(FIXTURE, "utf8"));

// The paths the comparison asks about: a unit's page, a directory redirect, an asset under
// a unit, a generated page outside every unit, engine chrome, and one that is not there.
const PATHS = [
  "/toolkit/map/", "/toolkit/map/index.html", "/toolkit/map", "/toolkit/map/app.js",
  "/playground/sketch/", "/index.html", "/__search.json", "/sw.js", "/nothing/here/",
];

/** A store holding the fixture, with a blob behind every hash it names. */
function fixtureEnv(ms) {
  const objects = new Map();
  for (const [id, m] of Object.entries(ms)) {
    objects.set(`spaces/${id}/manifest.json`, JSON.stringify(m));
    for (const f of Object.values(m.files || {})) objects.set(`blobs/${f.h}`, `blob:${f.h.slice(0, 8)}`);
  }
  return {
    GV_ASSET_SOURCE: "r2",
    BUNDLES: {
      async list({ prefix = "" } = {}) {
        return { delimitedPrefixes: Object.keys(ms).map((id) => `${prefix}${id}/`) };
      },
      async head(k) { return objects.has(k) ? { etag: `etag-${k}` } : null; },
      async get(k) {
        return objects.has(k) ? { text: async () => objects.get(k), body: objects.get(k) } : null;
      },
    },
  };
}

/**
 * Everything a manifest is read by, as one comparable document.
 *
 * `applyDerivedRouting` seeds the module's workspace context, which is why the gate and
 * the build stamp below are asked of the context it returns rather than of a second one.
 */
async function renderBundle() {
  const ms = manifests();
  W.applyInstance({ users: [{ email: "them@example.test", name: "Them", initials: "TH" }] });
  const ctx = W.applyDerivedRouting(ms);
  const derived = {};
  for (const k of [
    "BUILD_ID", "VERSION_MAP", "PUBLIC_PREFIXES", "PUBLIC_SKILL_PREFIXES", "RESTRICTED_BASES",
    "CANVAS_LOADER_EXTRAS", "CANVAS_CATALOG", "CANVAS_TRACKS",
    "MCP_HOST_ALLOWLIST", "MCP_PATH_ALLOWLIST", "SPACES", "CHROME_POINTER", "RUNTIME_CHROME",
  ]) derived[k] = ctx[k];

  const gate = {};
  for (const p of PATHS) gate[p] = { public: W.isPublicPath(ctx, p), version: W.versionFor(ctx, p) };

  // A tenant id nothing else in the suite uses, so the manifest cache this fills is this
  // file's own.
  const env = fixtureEnv(ms);
  const serve = {};
  for (const p of PATHS) {
    const res = await W.assetFetch("lineage-compat", env, new Request("https://x.test" + p));
    serve[p] = {
      status: res.status,
      location: res.headers.get("Location"),
      contentType: res.headers.get("Content-Type"),
      etag: res.headers.get("ETag"),
      cacheControl: res.headers.get("Cache-Control"),
      body: res.status === 200 ? await res.text() : null,
    };
  }

  return { derived, buildStamp: W.synthBuildStamp(ctx, ms), gate, serve };
}

if (process.argv.includes("--write")) {
  const at = (() => {
    try {
      return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
    } catch (e) { return "unknown"; }
  })();
  fs.writeFileSync(BASELINE, JSON.stringify({ generatedAt: at, ...(await renderBundle()) }, null, 2) + "\n");
  console.log(`baseline written from ${at}`);
} else {
  test("A MANIFEST WITH NO LINEAGE RENDERS EXACTLY AS IT DID BEFORE LINEAGE EXISTED", async () => {
    const was = JSON.parse(fs.readFileSync(BASELINE, "utf8"));
    const { generatedAt, ...expected } = was;
    assert.deepEqual(await renderBundle(), expected,
      "the fixture manifest renders differently than it did at " + generatedAt +
      " — an optional field changed the meaning of a manifest that does not carry it");
  });

  test("the fixture really is a pre-lineage manifest, so the comparison is not vacuous", () => {
    const raw = fs.readFileSync(FIXTURE, "utf8");
    assert.doesNotMatch(raw, /forkedFrom|unitOwners/, "the fixture has acquired the fields it exists to predate");
    // And it really is a manifest: two units, a file with no provenance stamp, an address.
    const alpha = manifests().alpha;
    assert.equal(alpha.routing.publicPrefixes.length, 2);
    assert.ok(!alpha.files["/toolkit/map/logo.svg"].by, "the un-stamped file has been stamped");
    assert.match(alpha.publishedBy, /@/, "the fixture no longer carries the address shape it exists to hold");
  });
}
