// Fork as a VERB — copying an artifact by aliasing its blobs, never by moving bytes.
//
// `F-fork-verb`. Forking already existed here twice, and neither one was a verb. It existed
// as conflict RESOLUTION (`C-fork-on-conflict`: two people edit the same unit, theirs keeps
// the URL, mine is re-keyed under a fork prefix), and it existed as "an agent copies a
// folder and publishes it" — which needs a repo, a checkout and an upload of every byte for
// content the store is already holding. Divergence-then-convergence as the collaboration
// model needs the deliberate one: take this artifact, give me my own copy of it, remember
// where it came from.
//
// ⚠️ IT IS THE SAME TRICK THE CONFLICT FORK USES, AND ON PURPOSE. A manifest maps a URL to a
// CONTENT HASH; the bytes live once in a content-addressed pool. So a copy is new manifest
// KEYS pointing at hashes the store already has — a hundred-file prototype forks without
// uploading, reading or hashing a single blob, and `bytesReferenced` does not move, because
// the fork references exactly the same blobs the source does. Inventing a second mechanism
// (re-upload, server-side blob copy) would cost bytes to produce a byte-identical result and
// would give the two forks two different definitions of what a copy is.
//
// ⚠️ THE COPY ESCAPES THE ORIGINAL'S ACL, which is the rule `B-resource-authz-hook` states:
// stamp the FORKER as the new unit's owner rather than inheriting the source's, or "fork it
// to get my own editable copy" hands the fork the same restriction it was forked to escape.
// The owner is a `personId`, never an address — see below.
//
// ⚠️ LINEAGE IS ADDITIVE AND OPTIONAL, so there is no flag day. `routing.forkedFrom` and
// `routing.unitOwners` are unit-keyed maps beside `unitSources`, which is already exactly
// this shape. A manifest that carries neither means today what it meant before they existed
// — `test/manifest-lineage-compat.test.mjs` renders a pre-lineage manifest against a
// baseline generated by the code that predates the fields, rather than asserting it.
//
// ⚠️ PEOPLE ARE `personId`, NEVER AN ADDRESS. Same deviation the per-file provenance stamp
// records at the commit handler, for the same reason: a manifest is read by more things than
// a comment thread is, and the store's manifests are readable by any holder of a publish
// token. The ONE field that carries an address is `publishedBy`, which predates all of this
// and has its own erasure path (`redactProvenance`); nothing this module writes adds a
// second one.
//
// ⚠️ NO NODE IMPORTS, and no hashing. The worker runs this module directly, so it may not
// reach for `node:crypto` — and it never needs to, because a fork computes no new bytes.

import { authoredUnits, unitPaths } from "./publish-units.mjs";
import { LITTER_RE } from "./publish-compose.mjs";

const dec = (s) => { try { return decodeURIComponent(String(s)); } catch (e) { return String(s); } };
const norm = (p) => String(p == null ? "" : p).replace(/\/?$/, "/");

/**
 * A fork TARGET is a plain path, and that is a deliberate narrowing.
 *
 * Manifest file keys are the literal decoded paths the build wrote; routing prefixes are
 * percent-encoded. Re-keying a hundred files across that seam is where an encoding bug would
 * live, so a new verb simply declines the ambiguity: a fork target is ASCII path segments,
 * and anything needing an escape is refused with a reason rather than guessed at. The SOURCE
 * is under no such rule — it is matched against the manifest's own spelling of its units, so
 * an already-published unit with an escaped name can still be forked.
 */
const PLAIN_PATH = /^\/(?:[A-Za-z0-9._~-]+\/)+$/;

/**
 * Compose the manifest a fork commits: live, plus one unit aliased at a new path.
 *
 *   live  — the live manifest (the fork is always OF what is live; forking a historical
 *           version would publish bytes no URL currently serves)
 *   from  — the source unit, any spelling of a `routing.publicPrefixes` entry
 *   to    — the new path
 *   by    — the forker's `personId`, or null when the caller cannot name one
 *
 * Returns `{manifest, aliased, sourceVersion}` or `{error, …}`. It reads no bytes and
 * computes no hashes: every entry it writes is a copy of an entry live already carries.
 */
export function composeFork({ live, from, to, by = null }) {
  const m = live || {};
  const files = m.files || {};
  const routing = m.routing || {};
  const src0 = norm(from), dst = norm(to);
  const bad = (reason) => ({ error: "bad-fork-path", reason });

  if (!src0.startsWith("/") || !dst.startsWith("/")) return bad("a fork path is absolute");
  if (dec(src0) === "/" || dec(dst) === "/") return bad("the site root is not an artifact");
  if (!PLAIN_PATH.test(dst)) return bad("a fork target is plain ASCII path segments");
  if (LITTER_RE.test(dec(dst))) return bad("`-conflict-` names belong to conflict forks");

  // A fork that nests inside its source (or contains it) puts one unit's files under
  // another's prefix, and `unitOfPath` resolves longest-prefix-wins — so the two would
  // disagree about which unit half the files belong to for the rest of the space's life.
  const sd = dec(src0), dd = dec(dst);
  if (sd === dd) return bad("a fork needs a path of its own");
  if (dd.startsWith(sd) || sd.startsWith(dd)) return bad("a fork cannot nest inside its source, or contain it");

  // Match the source against the manifest's OWN spelling of its units, so a caller may name
  // it either encoded or decoded and still hit the same unit.
  const units = authoredUnits(m);
  const src = [...units].find((u) => dec(u) === sd);
  if (!src) return { error: "unknown-unit", path: src0 };
  const paths = unitPaths(m, src);
  // A prefix with no files behind it serves nothing already — copying it would publish an
  // empty URL and call it an artifact.
  if (!paths.length) return { error: "unknown-unit", path: src0 };

  if (units.has(dst) || [...units].some((u) => dec(u) === dd)) return { error: "fork-target-exists", path: dst };
  for (const p of Object.keys(files)) {
    if (dec(p).startsWith(dd)) return { error: "fork-target-exists", path: dst };
  }

  const out = {
    ...m,
    files: { ...files },
    routing: {
      ...routing,
      publicPrefixes: [...(routing.publicPrefixes || [])],
      versionMap: { ...(routing.versionMap || {}) },
      unitSources: { ...(routing.unitSources || {}) },
      forkedFrom: { ...(routing.forkedFrom || {}) },
      unitOwners: { ...(routing.unitOwners || {}) },
    },
  };

  // The alias itself. The entry is copied WHOLE — hash, mime, size, and the per-file
  // provenance stamp the source carries. The bytes did not change, so neither did who last
  // changed them: restamping a hundred files with the forker is precisely the "a mass commit
  // reset every card to edited-now" failure `C-manifest-provenance` exists to retire. WHO
  // MADE THE COPY is a different fact, and it is `unitOwners` below.
  const aliased = [];
  for (const p of paths) {
    const q = dst + dec(p).slice(sd.length);
    out.files[q] = { ...files[p] };
    aliased.push([q, p]);
  }

  out.routing.publicPrefixes = [...new Set([...out.routing.publicPrefixes, dst])].sort();
  const vm = (routing.versionMap || {})[src];
  if (vm) out.routing.versionMap[dst] = vm;
  const us = (routing.unitSources || {})[src];
  // The fork's bytes came from that commit, whatever the forker has (or has not) checked out.
  if (us) out.routing.unitSources[dst] = { ...us };
  else if (m.source) out.routing.unitSources[dst] = { sha: m.source.sha || null, dirty: !!m.source.dirty };

  // The lineage record. The VERSION is live's, so "forked from /x/ at v41" names a manifest
  // the store still holds — versions are never pruned, so the parent is always recoverable
  // even after the source has moved on or been unpublished.
  out.routing.forkedFrom[dst] = { path: src, version: Number(m.version) || 0 };
  if (by) out.routing.unitOwners[dst] = by;

  return { manifest: out, aliased, from: src, to: dst, sourceVersion: Number(m.version) || 0 };
}

/**
 * Which unit-keyed lineage entries survive into the next manifest.
 *
 * ⚠️ THIS IS WHY A FORK DOES NOT EVAPORATE ON THE NEXT ORDINARY PUBLISH. A publisher's
 * manifest is built from their own tree and knows nothing about a fork somebody else made,
 * so a commit that took `routing` verbatim would drop the lineage and the owner while
 * keeping the files — the fork would still serve, and would have quietly become an
 * anonymous folder nobody owns.
 *
 * ⚠️ AND IT IS WHY OWNERSHIP IS NOT A FIELD YOU CAN TYPE. `B-resource-owner-schema-basis`'s
 * first rule is that an owner is stamped from the session and never read from the body; the
 * same has to hold here, or an ACL becomes a thing a publish can assert about itself. So
 * whatever the incoming manifest says is DISCARDED, and the answer is derived from what the
 * server already recorded, for the units that are still there.
 */
/**
 * The lineage a manifest may assert about ITSELF, when there is nothing to shadow.
 *
 * ⚠️ THIS EXISTS FOR ONE CALLER: A RESTORE INTO AN EMPTY STORE. `augur restore` (and the
 * migration built on it) replays an exported manifest as an ordinary publish, so a
 * workspace that is moved would otherwise arrive with its forks still serving and their
 * parentage and owners gone — silently, since nothing renders them yet.
 *
 * ⚠️ AND IT IS TRUST-ON-FIRST-PUBLISH, the pattern this handler already uses for
 * `space.adminOnly` and `space.default`: a claim is honoured only when the store holds no
 * prior value it could be overwriting. The moment there is one, `carriedLineage` decides and
 * the body is ignored, so no publish can ever reassign an owner by asserting one.
 *
 * The shapes are checked rather than trusted: an owner must look like a `personId` and MAY
 * NOT contain an address, so even the one trusted path cannot put one in a manifest, and a
 * lineage row must name a real declared unit.
 */
const PERSON_ID = /^[0-9a-z]{1,32}$/;

export function assertedLineage(routing) {
  const r = routing || {};
  const declared = new Set();
  for (const p of r.publicPrefixes || []) { declared.add(String(p)); declared.add(dec(p)); }
  const out = {};
  const from = r.forkedFrom;
  if (from && typeof from === "object" && !Array.isArray(from)) {
    const kept = {};
    for (const [u, v] of Object.entries(from)) {
      if (!declared.has(u) && !declared.has(dec(u))) continue;
      if (!v || typeof v !== "object" || typeof v.path !== "string" || !Number.isInteger(v.version)) continue;
      kept[u] = { path: v.path, version: v.version };
    }
    if (Object.keys(kept).length) out.forkedFrom = kept;
  }
  const owners = r.unitOwners;
  if (owners && typeof owners === "object" && !Array.isArray(owners)) {
    const kept = {};
    for (const [u, v] of Object.entries(owners)) {
      if (!declared.has(u) && !declared.has(dec(u))) continue;
      if (typeof v !== "string" || !PERSON_ID.test(v)) continue;
      kept[u] = v;
    }
    if (Object.keys(kept).length) out.unitOwners = kept;
  }
  return out;
}

export function carriedLineage(cur, nextRouting) {
  const prev = (cur && cur.routing) || {};
  const keep = new Set();
  for (const p of (nextRouting && nextRouting.publicPrefixes) || []) { keep.add(String(p)); keep.add(dec(p)); }
  const out = {};
  for (const field of ["forkedFrom", "unitOwners"]) {
    const from = prev[field];
    if (!from || typeof from !== "object") continue;
    const kept = {};
    for (const [u, v] of Object.entries(from)) if (keep.has(u) || keep.has(dec(u))) kept[u] = v;
    if (Object.keys(kept).length) out[field] = kept;
  }
  return out;
}
